### ISSUE TITLE
Problem including the Date header in the signature

### ISSUE THREAD

**Issue by mpuzar** [erasmus-without-paper/ewp-specs-sec-srvauth-httpsig#1]
While implementing the signature, I found out that the `Date `header is something that the application server (or possibly even apache & co. later) set _after_ the response is delivered and, as such, is out of our hands. And if I set the `Date` header myself, it is overwritten, invalidating the signature. 

To avoid having to look for ways to circumvent this problem for every possible implementation, I would suggest adding a custom date header instead (`X-Response-Signature-Date`, or maybe just `X-Date`?).

The same applies to generating signatures on the client side.

**Comment by wrygiel** [comment]
I don't think we should change that. This recommendation is part of the httpsig spec:

> The minimum recommended data to sign is the (request-target), host, and date.

By introducing alternative date headers, and by not signing the actual date header, we would be violating this recommendation.

**Comment by mpuzar** [comment]
I am just saying that it might technically be hard or impossible to adhere _strictly_ to this particular recommendation (it is only a SHOULD, not a MUST). By allowing to use an alternative date header instead, where the original `Date` is out of reach for the implementer, we would still _keep_ this recommended information, while also making it possible to implement where it otherwise would not be the case.

**Comment by wrygiel** [comment]
Please check if I understood you correctly:

### Solution 1

* Allow the signer to sign either `Date` *xor* `X-Date` header (but not both, I guess?)
* Require the verifier to support both.
  - If none of these two is signed, then verification will fail.
  - If the value of the signed one fails the threshold check, then verification will fail.
  - What to do when both `Date` *and* `X-Date` are signed? Fail? Verify any of them? Verify both of them?

**Comment by wrygiel** [comment]
I wonder what would be the best name for the `X-Date` header. Perhaps there already exists a standard one to handle this kind of scenario.

**Comment by wrygiel** [comment]
`X-Date` is a bad choice. Quote from RFC 6648:

```
   Creators of new parameters to be used in the context of application
   protocols:

   1.  SHOULD assume that all parameters they create might become
       standardized, public, commonly deployed, or usable across
       multiple implementations.

   2.  SHOULD employ meaningful parameter names that they have reason to
       believe are currently unused.

   3.  SHOULD NOT prefix their parameter names with "X-" or similar
       constructs.
```

`Response-Signature-Date` might be good for srvauth, but if we want to extend this to cliauth, then it fails.

**Comment by wrygiel** [comment]
`Signature-Date` would work, but it still fails to convey the actual meaning we are trying to get. We are not really interested in "the date it has been signed", but rather "the date is has been originally generated by the app" (and later we're signing this information to prove that it's correct).

Since Apache acts as a proxy here, and a proxy has a source/origin, then perhaps `Originating-Date` or `Origin-Date` would fit it best?

**Comment by wrygiel** [comment]
`Origin-Date` seems redundant though, because this is exactly how the `Date` header is documented as ([here](https://tools.ietf.org/html/rfc7231#section-7.1.1.2)):

> The "Date" header field represents the date and time at which the message was **originated** (...)
>
> When a Date header field is generated, the sender SHOULD generate its
> field value as the best available approximation of the date and time
> of message generation.  In theory, the date ought to represent the
> moment just before the payload is generated.  In practice, the date
> can be generated at any time during message origination.

*sigh*

`Original-Date`? (as in, "before it got replaced by proxy"?)

**Comment by mpuzar** [comment]
I'm fine with both `Original-Date`, `Signature-Date`, or even `Date-Signed`? Because, that is the main context and reason for it - signing.

As for the recipient - it will only check the headers mentioned in the `Authorization` header (and in that particular order), which is up to the sender to decide.

**Comment by wrygiel** [comment]
> As for the recipient - it will only check the headers mentioned in the `Authorization` header (and in that particular order), which is up to the sender to decide.

So, if the sender signs both `Date` and `Original-Date`, then the recipient is required to check both. Yes?

**Comment by mpuzar** [comment]
Yes, otherwise the signature verification will fail.

**Comment by wrygiel** [comment]
I'm not talking about signature verification. I'm talking about verifying the dates. See [here](https://github.com/erasmus-without-paper/ewp-specs-sec-srvauth-httpsig/tree/v0.2.0#verify-the-date).

**Comment by mpuzar** [comment]
Ah, I understand. Well, that is up to us to decide. It will probably not be a problem (I expect the difference to be max 1-2 s, unless one of the servers in the chain is misconfigured). I have no strong opinions here.

**Comment by wrygiel** [comment]
> The same applies to generating signatures on the client side.

Do you suspect that this problem also occurs in the `cliauth` case?

**Comment by mpuzar** [comment]
I suspect it might, but it really depends on how the clients are implemented and who is in control of the `Date` header there.

**Comment by wrygiel** [comment]
Went with:

### Solution 2

* Allow the signer to include and sign either `Date` *or* `Original-Date` header (or both).
* Require the verifier to support both.
  - If none of these two is signed, then verification will fail.
  - If the value of the signed one fails the threshold check, then verification will fail.
  - If both are included, then it's recommended for both to be verified, but it's not strictly required.
